import { useProjectStore } from '@/store/useProjectStore';
import { AppLayout } from '@/components/AppLayout';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Download, Share2, FileText, CheckCircle } from 'lucide-react';
import { useState } from 'react';

export default function ProposalBuilder() {
  const { selectedCommunity, selectedProblem, scenarios, simulationRuns, baselineData, setStep } = useProjectStore();
  const navigate = useNavigate();
  const [exported, setExported] = useState(false);

  const completedRuns = simulationRuns.filter((r) => r.status === 'complete');
  const bestRun = completedRuns[0];
  const bestScenario = scenarios[0];

  const totalCost = bestScenario?.interventions.reduce((s, i) => s + i.costEstimate, 0) || 0;

  const handleExport = () => {
    // Generate a simple text proposal
    const content = `
# Community Twin AI — Action Proposal

## Community
${selectedCommunity?.name || 'N/A'}, ${selectedCommunity?.region || 'N/A'}
Population: ${baselineData.population.toLocaleString()}

## Problem Focus
${selectedProblem?.title || 'N/A'}: ${selectedProblem?.description || ''}

## Proposed Interventions
${bestScenario?.interventions.map((i) => `- ${i.name}: ${i.description} ($${(i.costEstimate / 1000).toFixed(0)}K, ${i.timelineMonths} months)`).join('\n') || 'None'}

## Expected Impact
${bestRun?.outputs.map((o) => `- ${o.indicatorName}: ${o.baselineValue} → ${o.projectedValue} (${o.delta > 0 ? '+' : ''}${o.delta}, confidence: ${o.confidence}%)`).join('\n') || 'No simulation data'}

## Uncertainty
${bestRun?.uncertainty || 'N/A'}% — ${bestRun?.explanation || ''}

## Budget
Total estimated cost: $${(totalCost / 1000000).toFixed(2)}M

## Timeline
${bestScenario?.interventions.map((i) => `- ${i.name}: ${i.timelineMonths} months`).join('\n') || 'N/A'}

## Risks
- Implementation delays due to procurement
- Community adoption rates may vary
- Climate variability may affect environmental outcomes
- Budget overruns possible (±15% contingency recommended)

---
Generated by Community Twin AI | ${new Date().toLocaleDateString()}
    `.trim();

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `community-twin-proposal-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
    setExported(true);
  };

  const sections = [
    { title: 'Problem', content: `${selectedProblem?.title}: ${selectedProblem?.description || 'Not specified'}` },
    { title: 'Community', content: `${selectedCommunity?.name || 'N/A'}, ${selectedCommunity?.region || ''} — Pop. ${baselineData.population.toLocaleString()}` },
    { title: 'Evidence (Baseline)', content: `${Object.entries(baselineData).slice(0, 5).map(([k, v]) => `${k}: ${v}`).join(' • ')}` },
    { title: 'Interventions', content: bestScenario?.interventions.map((i) => `${i.name} ($${(i.costEstimate / 1000).toFixed(0)}K)`).join(', ') || 'None' },
    { title: 'Expected Impact', content: bestRun?.outputs.slice(0, 4).map((o) => `${o.indicatorName}: ${o.delta > 0 ? '+' : ''}${o.delta}`).join(' • ') || 'Run simulation first' },
    { title: 'Risks', content: 'Implementation delays, community adoption rates, climate variability, budget contingency (±15%)' },
    { title: 'Budget', content: `$${(totalCost / 1000000).toFixed(2)}M total estimated` },
    { title: 'Timeline', content: bestScenario?.interventions.map((i) => `${i.name}: ${i.timelineMonths}mo`).join(' • ') || 'N/A' },
  ];

  return (
    <AppLayout>
      <div className="container max-w-4xl mx-auto px-4 py-10">
        <div className="mb-8">
          <h1 className="text-2xl font-bold mb-2">Proposal Builder</h1>
          <p className="text-muted-foreground">Auto-generated evidence-based proposal ready for export and sharing.</p>
        </div>

        <div className="space-y-3 mb-8">
          {sections.map((s) => (
            <div key={s.title} className="bg-gradient-card border border-border rounded-xl p-5">
              <h3 className="text-xs font-semibold text-primary uppercase tracking-wider mb-2">{s.title}</h3>
              <p className="text-sm text-foreground/90 leading-relaxed">{s.content}</p>
            </div>
          ))}
        </div>

        {/* Second-order effects */}
        {bestRun && (
          <div className="bg-gradient-card border border-border rounded-xl p-5 mb-8">
            <h3 className="text-xs font-semibold text-primary uppercase tracking-wider mb-3">Second-Order Effects</h3>
            <ul className="space-y-1.5">
              {Array.from(new Set(bestRun.outputs.flatMap((o) => o.secondOrderEffects))).map((eff, i) => (
                <li key={i} className="text-sm text-muted-foreground flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-primary shrink-0" />
                  {eff}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Actions */}
        <div className="flex flex-wrap gap-3">
          <Button variant="outline" onClick={() => { setStep('comparison'); navigate('/comparison'); }}>
            <ArrowLeft className="w-4 h-4 mr-1" /> Compare
          </Button>
          <Button onClick={handleExport} className="bg-gradient-primary text-primary-foreground hover:opacity-90">
            {exported ? <CheckCircle className="w-4 h-4 mr-1" /> : <Download className="w-4 h-4 mr-1" />}
            {exported ? 'Downloaded!' : 'Export as Markdown'}
          </Button>
          <Button variant="outline" disabled>
            <FileText className="w-4 h-4 mr-1" /> PDF (Coming Soon)
          </Button>
          <Button variant="outline" disabled>
            <Share2 className="w-4 h-4 mr-1" /> Share (Requires Approval)
          </Button>
        </div>
      </div>
    </AppLayout>
  );
}
